In [1]:
# import the basic packages
import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings(action = "ignore")

---

In [2]:
# load the data
df = pd.read_csv("house_price_cleaned.csv")

In [3]:
# view
df[:2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-122.23,37.88,41,880,129.0,322,126,8.3252,NEAR BAY,452600
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY,358500

---

In [4]:
# null count
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
median_house_value    0
dtype: int64

In [5]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age      int64
total_rooms             int64
total_bedrooms        float64
population              int64
households              int64
median_income         float64
ocean_proximity        object
median_house_value      int64
dtype: object

---

In [6]:
# drop the ir-relevant columns
df = df.drop(columns = ["longitude", "latitude"], axis = 1)

In [7]:
# view
df[:2]

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,41,880,129.0,322,126,8.3252,NEAR BAY,452600
1,21,7099,1106.0,2401,1138,8.3014,NEAR BAY,358500

---

In [8]:
# label encoding
from sklearn.preprocessing import LabelEncoder

In [9]:
# call and assign
le = LabelEncoder()

In [10]:
# apply
df.ocean_proximity = le.fit_transform(df.ocean_proximity)

In [11]:
# view
df[:2]

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,41,880,129.0,322,126,8.3252,3,452600
1,21,7099,1106.0,2401,1138,8.3014,3,358500

---

In [12]:
# define X and y
X = df.drop("median_house_value", axis=1)

y = df["median_house_value"]

In [13]:
# model selection
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [15]:
# shape
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16512, 7), (4128, 7), (16512,), (4128,))

---

In [16]:
# model building
from sklearn.ensemble import RandomForestRegressor

In [17]:
model = RandomForestRegressor()

In [18]:
model

RandomForestRegressor()

---

In [19]:
model.fit(X_train, y_train)

RandomForestRegressor()

---

In [20]:
from sklearn.metrics import r2_score

In [21]:
y_pred = model.predict(X_test)

In [22]:
r2_score(y_test, y_pred)

0.6907655249776385

---

In [23]:
import joblib

In [24]:
# save the model
joblib.dump(model, "model.pkl")

['model.pkl']

In [25]:
joblib.dump(le, "label_encoder.pkl")

['label_encoder.pkl']

---